name: Kaabool Pro Builder
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Project and Apply Metadata
        run: |
          npx react-native init TempApp --version 0.73.0 --skip-install
          cp App.js TempApp/App.js
          
          # قراءة الإعدادات من كعبول (الاسم والإصدار)
          APP_NAME=$(jq -r '.name' kaabool-metadata.json)
          APP_VERSION=$(jq -r '.version' kaabool-metadata.json)
          
          cd TempApp
          # تغيير اسم التطبيق في الأندرويد
          sed -i "s/TempApp/$APP_NAME/g" android/app/src/main/res/values/strings.xml
          # تغيير الإصدار
          sed -i "s/versionName \"1.0\"/versionName \"$APP_VERSION\"/g" android/app/build.gradle
          
          npm install
      - name: Build APK
        run: |
          cd TempApp/android
          chmod +x gradlew
          ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: App-Release
          path: TempApp/android/app/build/outputs/apk/release/*.apk
